### ISSUE TITLE
hostname, apiVersion and apiKey in NetworkAbstraction.js are global variables, cannot create new instances

### ISSUE THREAD

**Issue by tyronedougherty** [Snowulf/oktajs#3]
After a frustrating day wondering why my code is returning incorrect results, I have found out the following bug occurs:

```
let instance1 = new OktaAPI('xxx-token1-xxx', 'xxx-domain1-xxx');
let instance2 = new OktaAPI('yyy-token2-yyy', 'yyy-domain2-yyy');

instance1.users.list({}, true, function (response) {
    console.log(response.resp); //User list here
});

instance2.users.list({}, true, function (response) {
    console.log(response.resp); //Is the exact same user listing here, despite having different credentials!!!
});
```

I believe this is due to line 8 of `NetworkAbstraction.js` in which the variables `hostname`, `apiVersion` and `apiKey` are declared globally. These credentials will be overwritten every time you `new` the `OktaAPI`, so all instances share them.

I'm considering making a pull request, do you accept pull requests?

**Comment by ShakataGaNai** [comment]
This didn't notify me either. Sorry. I shall figure out why that is.  PR merged.

**Comment by ShakataGaNai** [comment]
PS. Thank you very much!

**Comment by tyronedougherty** [comment]
@ShakataGaNai no worries!
